---
- hosts: ckan
  become: true
  vars:
    password: "{{ lookup('env','PASSWORD') }}"
  tasks:
    - name: Actualizar caché
      apt: update_cache=yes
    - name: Instalación de dependencias
      apt: name={{item}} state=installed
      with_items:
        -apache2
        -git-core
        -libapache2-mod-wsgi
        -libpq-dev
        -libpq5
        -nginx
        -openjdk-7-jdk
        -postgresql
        -python-dev
        -python-pastescript
        -python-pip
        -redis-server
        -solr-jetty
    - name: Comprobar si CKAN ya está instalado
      command: dpkg-query -W python-ckan
      register: instalado
      failed_when: instalado.rc > 1
      changed_when: instalado.rc == 1
    - block:
      - name: Descargar CKAN
        get_url:
          url: http://packaging.ckan.org/python-ckan_2.5-trusty_amd64.deb
          dest: /tmp
          mode: 0550
      - name: Instalar requisitos de CKAN
        pip: requirements=/usr/lib/ckan/default/src/ckan/requirements.txt
      when: instalado.rc == 1
    - name: Comprobar usuario de CKAN creado en base de datos
      command: if [ $(sudo -u postgres psql -t -c '\du' | cut -d \| -f 1 | grep -w ckan_default | wc -l) -eq 1 ]; then echo "true"; else return 1; fi
      register: usuario_creado
      failed_when: usuario_creado.rc > 1
      changed_when: usuario_creado.rc == 1
    - block:
      - name: Crear usuario de CKAN en base de datos
        command: sudo -u postgres psql -c "CREATE USER ckan_default WITH PASSWORD '{{ password }}';"
      - name: Comprobar tabla de CKAN creada en base de datos
        command: if [ $(sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -w ckan_default | wc -l) -eq 1 ]; then echo "true"; else return 1; fi
        register: tabla_creada
        failed_when: tabla_creada.rc > 1
        changed_when: tabla_creada.rc == 1
        - block:
          - name: Crear table de CKAN en base de datos
            command: sudo -u postgres createdb -O ckan_default ckan_default -E utf-8
          when: tabla_creada.rc > 1
      when: usuario_creado.rc > 1
