---
- hosts: ckan
  remote_user: vagrant
  become: true
  vars:
    version: "2.6"
    temp_dir: "/tmp"
    PASSWORD: "{{ lookup('env','PASSWORD') }}"
  tasks:
    - name: Update cache...
      apt: update_cache=yes
    - name: Install dependencies...
      apt: name={{item}} state=installed
      with_items:
        - apache2
        - git-core
        - libapache2-mod-wsgi
        - libpq-dev
        - libpq5
        - nginx
        - openjdk-7-jdk
        - postgresql
        - python-dev
        - python-pastescript
        - python-pip
        - redis-server
        - solr-jetty
    - name: Check if CKAN is already installed
      command: dpkg-query -W python-ckan | grep {{ version }}
      register: installed
      failed_when: installed.rc > 1
      changed_when: installed.rc == 1
    - block:
      - name: Download CKAN
        get_url:
          url: http://packaging.ckan.org/python-ckan_{{ version }}-trusty_amd64.deb
          dest: /tmp
          mode: 0550
#      - command: if [ $(dpkg-query -W python-ckan | wc -l) -eq 1]; then echo "true"; else return 1; fi
#        register: correct_version
#        failed_when: correct_version.rc > 1
#        changed_when: correct_version.rc == 1
#      - block:
#          - name: Uninstall previous version of CKAN
#            apt: name=python-ckan state=absent
#            when: correct_version.rc > 1
      - name: Install CKAN
        apt: deb="{{ temp_dir }}/python-ckan_{{ version }}-trusty_amd64.deb"
      - name: Install CKAN requirements
        pip: requirements=/usr/lib/ckan/default/src/ckan/requirements.txt
      when: installed.rc == 1
