---
- hosts: ckan
  remote_user: vagrant
  become: true
  vars:
    PASSWORD: "{{ lookup('env','PASSWORD') }}"
  tasks:
    - name: Actualización de paquetes
      apt:
        update_cache=yes
        cache_valid_time=1800
        upgrade=safe
        dpkg_options='force-confold'
    - name: Instalación de dependencias
      apt:
        name={{ item }}
        state=latest
        dpkg_options='force-confold'
      with_items:
        - apache2
        - git-core
        - libapache2-mod-wsgi
        - libpq-dev
        - libpq5
        - nginx
        - openjdk-7-jdk
        - postgresql
        - python-dev
        - python-pastescript
        - python-pip
        - redis-server
        - solr-jetty
